export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';

export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST';
export const PRODUCTS_LIST_RECEIVED = 'PRODUCTS_LIST_RECEIVED';
export const PRODUCTS_LIST_ERROR = 'PRODUCTS_LIST_ERROR';





