export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST';
export const PRODUCTS_LIST_RECEIVED = 'PRODUCTS_LIST_RECEIVED';
export const PRODUCTS_LIST_ERROR = 'PRODUCTS_LIST_ERROR';

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';


